### ISSUE TITLE
Fake time data for missing time in gpx file

### ISSUE THREAD

**Issue by l-kah** [kf99916/gpx-parser-builder#13]
Hello.
If a file does not have a timestamp in the trackpoints, it seems that the parser will create one based on the current time.
This is very misleading for doing calculations and so on. I would prefer to not have the a time entry at all if it is missing in the original file.

Thanks
Lars

**Comment by kf99916** [comment]
Hi @l-kah , fixed at 21b85acf3d320409b99866c2e467263237ab0252.
